appearance:
  font_family: Arial
  font_size: 12
  theme: light
connection:
  auto_reconnect: true
  keep_alive_interval: 60
  timeout: 30
logging:
  level: INFO
  max_log_files: 10
  max_log_size_mb: 10
transfer:
  confirm_local_to_remote: true
  confirm_overwrites: true
  confirm_remote_to_local: true
  create_missing_directories: true
  default_local_path: /Users/pythax
  preserve_timestamps: true
window:
  height: 800
  maximized: false
  remember_size: true
  width: 1200
